input {
  # Subscribe 3 topics from Kafka
  kafka { 
    bootstrap_servers => "elk_lab-kafka-1:9092"
    topics => ["logs-login", "logs-payment", "logs-click"]
    group_id => "logstash-unified-group"
    codec => "json"
    consumer_threads => 3
    decorate_events => true 
  }
}

filter {
  # time parsing
  date {
    match => [ "timestamp", "ISO8601" ]
    target => "@timestamp"
  }

  # Extract topic name from kafka
  # ex: [@metadata][kafka][topic] -> "logs-payment"
  mutate {
    add_field => { "kafka_topic" => "%{[@metadata][kafka][topic]}" }
  }

  # Add tag for payment 
  if [log_type] == "payment" {
    mutate {
      add_tag => [ "high_priority" ]
    }
  }
}

output {
  # Elasticsearch 
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "unified-logs-%{+YYYY.MM.dd}"
  }

  # S3(data lake)
  s3 {
    access_key_id => "${AWS_ACCESS_KEY_ID}"    
    secret_access_key => "${AWS_SECRET_ACCESS_KEY}"
    region => "ap-northeast-2"
    bucket => "tajung-elk-bucket"
    
    # Topic name + datetime
    # ex: logs-payment/year=2026/month=02/day=22/
    prefix => "%{kafka_topic}/year=%{+YYYY}/month=%{+MM}/day=%{+dd}/"
    
    # File creation
    size_file => 10485760  # 10MB
    time_file => 1         # 1min
    codec => "json_lines"
  }

  # Terminal
  stdout { codec => rubydebug }
}